In [17]:
import pandas as pd
import numpy as np
import datetime as dt

In [18]:
jan2021 = "Data/2021/JC-202101-citibike-tripdata.csv"
feb2021 = "Data/2021/JC-202102-citibike-tripdata.csv"
mar2021 = "Data/2021/JC-202103-citibike-tripdata.csv"
apr2021 = "Data/2021/JC-202104-citibike-tripdata.csv"
may2021 = "Data/2021/JC-202105-citibike-tripdata.csv"
jun2021 = "Data/2021/JC-202106-citibike-tripdata.csv"
jul2021 = "Data/2021/JC-202107-citibike-tripdata.csv"
aug2021 = "Data/2021/JC-202108-citibike-tripdata.csv"
sep2021 = "Data/2021/JC-202109-citibike-tripdata.csv"
oct2021 = "Data/2021/JC-202110-citibike-tripdata.csv"

In [19]:
jan2021_df = pd.read_csv(jan2021)
feb2021_df = pd.read_csv(feb2021)
mar2021_df = pd.read_csv(mar2021)
apr2021_df = pd.read_csv(apr2021)
may2021_df = pd.read_csv(may2021)
jun2021_df = pd.read_csv(jun2021)
jul2021_df = pd.read_csv(jul2021)
aug2021_df = pd.read_csv(aug2021)
sep2021_df = pd.read_csv(sep2021)
oct2021_df = pd.read_csv(oct2021)

In [24]:
jan2021_df.count()

tripduration               11624
starttime                  11624
stoptime                   11624
start station id           11624
start station name         11624
start station latitude     11624
start station longitude    11624
end station id             11624
end station name           11624
end station latitude       11624
end station longitude      11624
bikeid                     11624
usertype                   11624
birth year                 11624
gender                     11624
dtype: int64

In [25]:
# Convert All DateTimes to "%Y-%m-%d %H:%M:%S" Format
jan2021_df["starttime"] = pd.to_datetime(jan2021_df["starttime"])
jan2021_df["stoptime"] = pd.to_datetime(jan2021_df["stoptime"])

In [26]:
Clean_jan2021_df = jan2021_df.drop(columns=['birth year', 'gender', 'bikeid'])

In [27]:
Clean_jan2021_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,usertype
0,266,2021-01-01 00:03:35.510,2021-01-01 00:08:01.777,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,Subscriber
1,1543,2021-01-01 00:23:32.925,2021-01-01 00:49:16.083,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,Customer
2,1461,2021-01-01 00:23:50.794,2021-01-01 00:48:12.566,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,Customer
3,793,2021-01-01 00:31:09.077,2021-01-01 00:44:22.943,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,Customer
4,596,2021-01-01 00:35:52.190,2021-01-01 00:45:48.774,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,Customer
...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.470,2021-01-31 20:57:22.011,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,Subscriber
11620,147,2021-01-31 21:05:05.209,2021-01-31 21:07:32.866,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,Subscriber
11621,660,2021-01-31 21:06:23.588,2021-01-31 21:17:23.842,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,Subscriber
11622,384,2021-01-31 21:16:37.822,2021-01-31 21:23:02.124,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,Subscriber
11623,356,2021-01-31 23:24:50.881,2021-01-31 23:30:47.303,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,Subscriber

In [63]:
Clean_jan2021_df['usertype'].replace('Subscriber','member',inplace = True)

In [64]:
Clean_jan2021_df['usertype'].replace('Customer','casual',inplace = True)

In [65]:
Clean_jan2021_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,usertype
0,266,2021-01-01 00:03:35.510,2021-01-01 00:08:01.777,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,member
1,1543,2021-01-01 00:23:32.925,2021-01-01 00:49:16.083,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,casual
2,1461,2021-01-01 00:23:50.794,2021-01-01 00:48:12.566,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,casual
3,793,2021-01-01 00:31:09.077,2021-01-01 00:44:22.943,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,casual
4,596,2021-01-01 00:35:52.190,2021-01-01 00:45:48.774,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,casual

In [66]:
Clean_jan2021_df.count()

tripduration               11624
starttime                  11624
stoptime                   11624
start station id           11624
start station name         11624
start station latitude     11624
start station longitude    11624
end station id             11624
end station name           11624
end station latitude       11624
end station longitude      11624
usertype                   11624
dtype: int64

In [67]:
feb2021_df.count()

ride_id               4881
rideable_type         4881
started_at            4881
ended_at              4881
start_station_name    4881
start_station_id      4881
end_station_name      4813
end_station_id        4813
start_lat             4881
start_lng             4881
end_lat               4813
end_lng               4813
member_casual         4881
dtype: int64

In [68]:
feb2021_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,3F8FD9A051C0E3DA,docked_bike,2021-02-24 18:05:45,2021-02-24 18:12:27,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4877,B91F3593C0C06D04,docked_bike,2021-02-22 18:22:04,2021-02-22 18:28:45,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4878,A790954A017D07CB,docked_bike,2021-02-13 12:21:49,2021-02-13 12:27:51,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4879,42B1932D06CEE034,docked_bike,2021-02-25 11:20:29,2021-02-25 11:25:23,Columbus Drive,JC014,Morris Canal,JC072,40.718355,-74.038914,40.712419,-74.038526,member
4880,F71732ECE7CD02CF,docked_bike,2021-02-19 13:59:22,2021-02-19 14:05:47,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member

In [9]:
oct2021_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0FA0B0B972A68AAB,classic_bike,2021-10-19 06:08:46,2021-10-19 06:11:26,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
1,0702BED6EB379838,classic_bike,2021-10-16 12:08:29,2021-10-16 12:13:29,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
2,A8810ECCC69E2866,classic_bike,2021-10-29 12:29:49,2021-10-29 12:34:49,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
3,C9A0FF2B82237FFA,classic_bike,2021-10-08 12:36:21,2021-10-08 12:40:55,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
4,7DFDEB8EF4CAB15C,classic_bike,2021-10-14 06:54:51,2021-10-14 07:01:14,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88757,2B1145DCE1C12234,classic_bike,2021-10-22 21:33:14,2021-10-22 21:56:13,Clinton St & 7 St,HB303,City Hall - Washington St & 1 St,HB105,40.745420,-74.033320,40.737360,-74.030970,casual
88758,9332D910D93C0961,classic_bike,2021-10-16 14:30:26,2021-10-16 14:35:43,Clinton St & 7 St,HB303,City Hall - Washington St & 1 St,HB105,40.745420,-74.033320,40.737360,-74.030970,casual
88759,9BD55309848AD745,classic_bike,2021-10-17 02:11:58,2021-10-17 02:18:26,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual
88760,263F1EE58709CB6D,classic_bike,2021-10-07 20:38:47,2021-10-07 20:44:49,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual
88761,2D38261C42BE80F3,classic_bike,2021-10-23 23:48:08,2021-10-23 23:55:02,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual

In [69]:
febthruoct_df = feb2021_df.append([mar2021_df, apr2021_df, may2021_df, jun2021_df, jul2021_df, aug2021_df, sep2021_df, oct2021_df], ignore_index=True)
febthruoct_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member

In [70]:
febthruoct_df.count()

ride_id               524650
rideable_type         524650
started_at            524650
ended_at              524650
start_station_name    524650
start_station_id      524650
end_station_name      522045
end_station_id        522045
start_lat             524650
start_lng             524650
end_lat               522844
end_lng               522844
member_casual         524650
dtype: int64

In [71]:
# Convert All DateTimes to "%Y-%m-%d %H:%M:%S" Format
febthruoct_df["started_at"] = pd.to_datetime(febthruoct_df["started_at"])
febthruoct_df["ended_at"] = pd.to_datetime(febthruoct_df["ended_at"])

In [72]:
Clean_jan2021_df.count()

tripduration               11624
starttime                  11624
stoptime                   11624
start station id           11624
start station name         11624
start station latitude     11624
start station longitude    11624
end station id             11624
end station name           11624
end station latitude       11624
end station longitude      11624
usertype                   11624
dtype: int64

In [105]:
febthruoct_df["tripduration"] = febthruoct_df["ended_at"]- febthruoct_df["started_at"]

In [108]:
febthruoct_df["tripduration"] = febthruoct_df["tripduration"]/np.timedelta64(1,'s')

In [110]:
febthruoct_df_reorder = febthruoct_df[['ride_id','rideable_type','tripduration','started_at','ended_at','start_station_id','start_station_name','start_lat','start_lng','end_station_id','end_station_name','end_lat','end_lng','member_casual']]

In [111]:
febthruoct_df_reorder.count()

ride_id               524650
rideable_type         524650
tripduration          524650
started_at            524650
ended_at              524650
start_station_id      524650
start_station_name    524650
start_lat             524650
start_lng             524650
end_station_id        522045
end_station_name      522045
end_lat               522844
end_lng               522844
member_casual         524650
dtype: int64

In [112]:
febthruoct_df_reorder_rename = febthruoct_df_reorder.rename(columns={"started_at": "starttime",
                                            "ended_at": "stoptime",
                                            "start_station_id": "start station id",
                                            "start_station_name": "start station name",
                                            "start_lat": "start station latitude",
                                            "start_lng": "start station longitude",
                                            "end_station_id": "end station id",
                                            "end_station_name": "end station name",
                                            "end_lat": "end station latitude",
                                            "end_lng": "end station longitude",
                                            "member_casual": "usertype",
                                           })
febthruoct_df_reorder_rename

,ride_id,rideable_type,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,usertype
0,121DD7DD23CB1335,docked_bike,420.0,2021-02-03 23:11:28,2021-02-03 23:18:28,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046964,JC034,Christ Hospital,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,1355.0,2021-02-27 16:34:05,2021-02-27 16:56:40,JC008,Newport Pkwy,40.728744,-74.032108,JC013,Marin Light Rail,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,381.0,2021-02-26 23:16:04,2021-02-26 23:22:25,JC103,Journal Square,40.733670,-74.062500,JC020,Baldwin at Montgomery,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,1459.0,2021-02-24 16:51:50,2021-02-24 17:16:09,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046963,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,30.0,2021-02-24 20:44:16,2021-02-24 20:44:46,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046963,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524645,2B1145DCE1C12234,classic_bike,1379.0,2021-10-22 21:33:14,2021-10-22 21:56:13,HB303,Clinton St & 7 St,40.745420,-74.033320,HB105,City Hall - Washington St & 1 St,40.737360,-74.030970,casual
524646,9332D910D93C0961,classic_bike,317.0,2021-10-16 14:30:26,2021-10-16 14:35:43,HB303,Clinton St & 7 St,40.745420,-74.033320,HB105,City Hall - Washington St & 1 St,40.737360,-74.030970,casual
524647,9BD55309848AD745,classic_bike,388.0,2021-10-17 02:11:58,2021-10-17 02:18:26,HB303,Clinton St & 7 St,40.745420,-74.033320,HB506,Grand St & 14 St,40.754090,-74.031600,casual
524648,263F1EE58709CB6D,classic_bike,362.0,2021-10-07 20:38:47,2021-10-07 20:44:49,HB303,Clinton St & 7 St,40.745420,-74.033320,HB506,Grand St & 14 St,40.754090,-74.031600,casual
524649,2D38261C42BE80F3,classic_bike,414.0,2021-10-23 23:48:08,2021-10-23 23:55:02,HB303,Clinton St & 7 St,40.745420,-74.033320,HB506,Grand St & 14 St,40.754090,-74.031600,casual

In [113]:
febthruoct_df_reorder_rename['tripduration'].max()

9020291.0

In [115]:
Clean_febthruoct_df_reorder_rename = febthruoct_df_reorder_rename.drop(columns=['ride_id', 'rideable_type'])

In [116]:
Clean_febthruoct_df_reorder_rename.count()

tripduration               524650
starttime                  524650
stoptime                   524650
start station id           524650
start station name         524650
start station latitude     524650
start station longitude    524650
end station id             522045
end station name           522045
end station latitude       522844
end station longitude      522844
usertype                   524650
dtype: int64

In [117]:
Clean_jan2021_df.count()

tripduration               11624
starttime                  11624
stoptime                   11624
start station id           11624
start station name         11624
start station latitude     11624
start station longitude    11624
end station id             11624
end station name           11624
end station latitude       11624
end station longitude      11624
usertype                   11624
dtype: int64

In [118]:
Clean_febthruoct_df_reorder_rename.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,usertype
0,420.0,2021-02-03 23:11:28,2021-02-03 23:18:28,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046964,JC034,Christ Hospital,40.734786,-74.050444,member
1,1355.0,2021-02-27 16:34:05,2021-02-27 16:56:40,JC008,Newport Pkwy,40.728744,-74.032108,JC013,Marin Light Rail,40.714584,-74.042817,member
2,381.0,2021-02-26 23:16:04,2021-02-26 23:22:25,JC103,Journal Square,40.733670,-74.062500,JC020,Baldwin at Montgomery,40.723659,-74.064194,member
3,1459.0,2021-02-24 16:51:50,2021-02-24 17:16:09,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046963,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046964,casual
4,30.0,2021-02-24 20:44:16,2021-02-24 20:44:46,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046963,JC105,Hoboken Ave at Monmouth St,40.735208,-74.046964,member

In [131]:
Clean_BikeData_2021_df = Clean_jan2021_df.append([Clean_febthruoct_df_reorder_rename])

In [132]:
Clean_BikeData_2021_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,usertype
0,266.0,2021-01-01 00:03:35.510,2021-01-01 00:08:01.777,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,member
1,1543.0,2021-01-01 00:23:32.925,2021-01-01 00:49:16.083,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,casual
2,1461.0,2021-01-01 00:23:50.794,2021-01-01 00:48:12.566,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,casual
3,793.0,2021-01-01 00:31:09.077,2021-01-01 00:44:22.943,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,casual
4,596.0,2021-01-01 00:35:52.190,2021-01-01 00:45:48.774,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,casual

In [133]:
Clean_BikeData_2021_df.count()

tripduration               536274
starttime                  536274
stoptime                   536274
start station id           536274
start station name         536274
start station latitude     536274
start station longitude    536274
end station id             533669
end station name           533669
end station latitude       534468
end station longitude      534468
usertype                   536274
dtype: int64

In [ ]:
Clean_BikeData_2021_df.to_csv("Source/Clean_BikeData_2021_df.csv", index=False, header=True)